version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-updates:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"   # Alle Go-Abhängigkeiten
      major-updates:
        update-types:
          - "major"
        patterns:
          - "*"   # Alle Go-Abhängigkeiten
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch-updates:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"   # Alle Docker-Images
      major-updates:
        update-types:
          - "major"
        patterns:
          - "*"   # Alle Docker-Images
    commit-message:
      prefix: "deps"
      include: "scope"