version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"  # Pfad zu go.mod
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      go-dependencies:
        patterns:
          - "*"  # Gruppiert alle Go-Abhängigkeiten
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      docker-updates:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"