name: Run Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build

      - name: Test
        run: go test

      - name: Build Docker container
        run: make build

      - name: Run Docker container
        run: make test

      - name: Build native
        run: make go-build.release
