name: Run Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Download go
        run: go mod download

      - name: Build Docker container
        run: make build

      - name: Build native files
        run: make go-build-release
